### ISSUE TITLE
Compilation Fails

### ISSUE THREAD

**Issue by AntonyChiossi** [martelletto/fido2-webauthn-client#1]
I tried to compile it and is seems a reference is missing. I got it work by commenting that part of the code.

> if (b64_len < 0 || /*(size_t)b64_len == SIZE_MAX ||*/ b64_ptr == NULL)
		goto fail;

BUILD 

> fido2-webauthn-client git:(master) ✗ make -C build
make: Entering directory '/home/vm/to_delete/fido2-webauthn-client/build'
/usr/bin/cmake -H/home/vm/to_delete/fido2-webauthn-client -B/home/vm/to_delete/fido2-webauthn-client/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/vm/to_delete/fido2-webauthn-client/build/CMakeFiles /home/vm/to_delete/fido2-webauthn-client/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/vm/to_delete/fido2-webauthn-client/build'
make -f CMakeFiles/fido2-webauthn-client.dir/build.make CMakeFiles/fido2-webauthn-client.dir/depend
make[2]: Entering directory '/home/vm/to_delete/fido2-webauthn-client/build'
cd /home/vm/to_delete/fido2-webauthn-client/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/vm/to_delete/fido2-webauthn-client /home/vm/to_delete/fido2-webauthn-client /home/vm/to_delete/fido2-webauthn-client/build /home/vm/to_delete/fido2-webauthn-client/build /home/vm/to_delete/fido2-webauthn-client/build/CMakeFiles/fido2-webauthn-client.dir/DependInfo.cmake
Scanning dependencies of target fido2-webauthn-client
make[2]: Leaving directory '/home/vm/to_delete/fido2-webauthn-client/build'
make -f CMakeFiles/fido2-webauthn-client.dir/build.make CMakeFiles/fido2-webauthn-client.dir/build
make[2]: Entering directory '/home/vm/to_delete/fido2-webauthn-client/build'
[ 11%] Building C object CMakeFiles/fido2-webauthn-client.dir/base64.c.o
/usr/bin/cc    -Wall -Wextra -Werror -Wshadow -Wwrite-strings -Wmissing-prototypes -Wbad-function-cast -pedantic -pedantic-errors   -o CMakeFiles/fido2-webauthn-client.dir/base64.c.o   -c /home/vm/to_delete/fido2-webauthn-client/base64.c
/home/vm/to_delete/fido2-webauthn-client/base64.c: In function ‘base64_encode’:
/home/vm/to_delete/fido2-webauthn-client/base64.c:92:40: error: ‘SIZE_MAX’ undeclared (first use in this function)
  if (b64_len < 0 || (size_t)b64_len == SIZE_MAX || b64_ptr == NULL)
                                        ^
/home/vm/to_delete/fido2-webauthn-client/base64.c:92:40: note: each undeclared identifier is reported only once for each function it appears in
CMakeFiles/fido2-webauthn-client.dir/build.make:65: recipe for target 'CMakeFiles/fido2-webauthn-client.dir/base64.c.o' failed
make[2]: *** [CMakeFiles/fido2-webauthn-client.dir/base64.c.o] Error 1
make[2]: Leaving directory '/home/vm/to_delete/fido2-webauthn-client/build'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/fido2-webauthn-client.dir/all' failed
make[1]: *** [CMakeFiles/fido2-webauthn-client.dir/all] Error 2
make[1]: Leaving directory '/home/vm/to_delete/fido2-webauthn-client/build'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/home/vm/to_delete/fido2-webauthn-client/build'

**Comment by martelletto** [comment]
Fixed in afe5a259. Thank you for the report!
