### ISSUE TITLE
[Question] Is it possible to use endpoints that requires login?

### ISSUE THREAD

**Issue by AntonyChiossi** [martelletto/fido2-webauthn-client#2]
For example, in the deprecated tool _u2f-host_ one was able to register before the registration / auth phase.

https://developers.yubico.com/libu2f-host/

> curl 'https://demo.yubico.com/wsapi/u2f/enroll?username=jas&password=foo' > foo

I was scanning the source code (im not fluent in C) but i looks like it is currently not supported right?

Thanks in advance!

**Comment by martelletto** [comment]
You are right; fido2-webauthn-client includes this step, so it cannot be done outside the tool.

**Comment by AntonyChiossi** [comment]
@martelletto ok, so is it possible to login (I mean the first step of the login, not the 2FA request)  within the tool?

to be clear, here the expected flow:

1. login (set session cookies)
2. registration request (needs session cookies)
3. registration verify (needs session cookies)

**Comment by martelletto** [comment]
It depends on the RP (server) and what the expected login process entails. The tool follows the steps required by demo.yubico.com. You may need to change a few settings in param.h and the *_parse_response() functions in webauthn-cred.c.
